### ISSUE TITLE
Deriving Serializable automatically

### ISSUE THREAD

**Issue by bbarker** [agocorona/TCache#11]
I've defined an abstract record type`IsCowRec` below. I was able to use `{-# LANGUAGE DerivingVia #-}` successfully on concrete data types implementing `IsCowRec`, e.g. `deriving (Indexable, Ord, Serializable) via WrappedCRK SxRecord`, for `Indexable`, but not for `Serializable`. This seems to be how `read` may be used within TCache itself, as I'm getting this exception: `EXCEPTION: Prelude.read: no parse ` when I try various things, including what I have below (probably not ideal). Note that `Serializable` was working when I implement it just as below for individual concrete datatypes. 

Is there a way to accomplish this ? Not a show stopper if not, as it is just copy/pasting a few lines of code, but curious.

```haskell
{-# LANGUAGE MonoLocalBinds       #-}
{-# LANGUAGE FlexibleInstances    #-}
{-# LANGUAGE TypeSynonymInstances #-}

module FDS.Data.IsRecord where

-- import           Control.Arrow
import qualified Data.ByteString.Lazy.Char8       as DBS (pack, unpack)
import           Data.TCache                      hiding(atomically)
import           Data.TCache.DefaultPersistence
import           FDS.Data.Common
import           FDS.Data.Util
import           Text.Read                        (read)

type CowRecordKey = (CowMark, UTCTime)

class (Eq a, IResource a, Ord a, Read a, Show a, Typeable a)
  => IsCowRec a where
  recKeyAccessors   :: (a -> CowMark, a-> UTCTime)
  recKeyAccessors   = toFunTuple2 recKey
  recKey            :: a -> CowRecordKey
  partialRecByKey   :: CowRecordKey -> a
  insertRecs        :: [a] -> IO ()
  insertRecs recs = withResources [] (storeIt recs)
    where
      storeIt :: [a] -> [Maybe a] -> [a]
      storeIt rs _ = rs

newtype WrappedCRK a = WrapCRK { unwrapCRK :: a }
  deriving (Eq, Show, Read)

instance IsCowRec a => Ord (WrappedCRK a) where
  WrapCRK r1 `compare` WrapCRK r2 = recKey r1 `compare` recKey r2

--TODO: make windows-friendly filename (formatFdsTime)
instance IsCowRec a => Indexable (WrappedCRK a) where
  key cowrec = (show miInt) ++ "_" ++ formatFdsTime timeIn
    where
      (markIn, timeIn) = recKey $ unwrapCRK cowrec
      CowMark (miInt) = markIn

instance IsCowRec a => Serializable (WrappedCRK a) where
  serialize = DBS.pack . show
  deserialize = read . DBS.unpack
  -- | No need to specify setPerist if using file persistence
  -- setPersist = Just ___
```

**Comment by bbarker** [comment]
Actually, this `EXCEPTION: Prelude.read: no parse` appears to be an unrelated but more serious and mysterious issue. I reverted to a prior commit that I knew was previously working, and it is now failing, with the same data.

**Comment by bbarker** [comment]
I believe, but am not sure, that my problem has to do with a test framework sometimes prematurely ending a test: https://github.com/joelburget/easytest/issues/21

Also, as it pertains to the original issue at hand, here is how I implemented the generic Serializable instance: 

```haskell
instance IsCowRec a => Serializable (WrappedCRK a) where
  serialize = DBS.pack . show . unwrapCRK
  deserialize = WrapCRK . read . DBS.unpack
```

**Comment by agocorona** [comment]
Hi bbarker,  First time that I show this. It was lost in my notifications.
Tomorrow I will take a look.

**Comment by bbarker** [comment]
Hi @agocorona - yes, I believe this was related to the other issue I surfaced in #13, and is now resolved and I'm happy with how this aspect of TCache is working.
