### ISSUE TITLE
Threading DB state into Persist

### ISSUE THREAD

**Issue by bbarker** [agocorona/TCache#12]
I'd like to understand how to do this. E.g. `readByKey   ::  (Key -> IO(Maybe B.ByteString))` would normally rely on a database reference, but since this is an instance function and not something that I as a user of the library am calling directly, I don't think I can thread in an environment through e.g. a Reader monad.

**Comment by bbarker** [comment]
Actually, at first glance it seems like I may be able to (indirectly) solve this issue using `setDefaultPersist :: Persist -> IO ()`, which I hadn't noticed before - will experiment more soon.

**Comment by agocorona** [comment]
I hope that setDefaultPersist solves your requirement.

**Comment by bbarker** [comment]
Yes, it seems to though I have a related issue related to strictness - but will open another github issue for that.
